# Copyright (c) 2023 Lite XL Contributors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

FROM quay.io/pypa/manylinux2014_x86_64

# these files are from RHEL8
ADD libdecor-devel-0.1.0-3.el8.x86_64.rpm libdecor-0.1.0-3.el8.x86_64.rpm /

# install deps
RUN yum -y update && yum clean all && \
	yum -y install rh-python38 ccache fuse fuse3 sudo \
	libX11-devel libXi-devel libXcursor-devel libxkbcommon-devel libXrandr-devel wayland-devel wayland-protocols-devel dbus-devel ibus-devel SDL2-devel \
	gcc-aarch64-linux-gnu gcc-c++-aarch64-linux-gnu binutils-aarch64-linux-gnu

# install meson and ninja
RUN source /opt/rh/rh-python38/enable && pip3 install meson ninja

# install libdecor
RUN rpm -ivh --nodeps libdecor-devel-0.1.0-3.el8.x86_64.rpm
RUN rpm -ivh --nodeps libdecor-0.1.0-3.el8.x86_64.rpm

ADD entrypoint-manylinux.sh /entrypoint.sh

